[package]
name = "tablix-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
engine = { path = "../engine" }
pivot-engine = { path = "../pivot-engine" }
